BUG-98627: Mtastore resource lookup is failing due to NoClassDefFoundError
Change-Id: Id47382fca25e659ed0b2b10fcb879dfc5ff6de17
Signed-off-by: rmani <rmani@hortonworks.com>