BUG-92602: NoClassDefFoundError during ranger plugin enabling due to unavailability of dependencies
Change-Id: Ic5788f32ef2cd3f5ef47338ce3dbff72bc0d5b46